---
title: "bitcoin"
output: pdf_document
---

```{r cars, echo=TRUE, paged.print=TRUE}
library(quantmod)
library(ggplot2)
library(forecast)
library(tseries)
library(rugarch)
library(prophet)
library(tsfknn)


#bitcoin data ARIMA
library(readr)

bit <- read_csv("Bitcoin_historica_data.csv")
bit$Date <- as.Date(bit$Date)

library(dplyr)
bit<-arrange(bit,Date)


bit1 <- ts(bit$Price)

#test the stationary
print(adf.test(bit1))

#plot the data
autoplot(bit1)+ ylab("Bitcoin Close Price") + xlab("Days")

bit365 <- ts(bit$Price,frequency = 365,start = c(2010))
autoplot(bit365)+ ylab("Bitcoin Close Price") + xlab("Year")

#max close price of bitcoin since its existence
max(bit1)
```



```{r cars, echo=TRUE, paged.print=TRUE}
#transformation
#boxcox
lm <- BoxCox.lambda(bit1)
bit_bc <- BoxCox(bit1,lambda=lm)
autoplot(bit_bc)
#auto lambda
bit_bc <- BoxCox(bit1,lambda="auto")
autoplot(bit_bc)+ ylab("Bitcoin Close Price") + xlab("Days")

#differencing
ggtsdisplay(diff(bit_bc,lag=1))

library(urca)
bit_bc %>% diff(lag=1) %>% ur.kpss() %>% summary()
bit_bc  %>% diff(lag=1) %>% ndiffs()

#model

fit <- auto.arima(bit_bc, lambda="auto")
fit <- auto.arima(bit_bc)
fit$aicc
summary(fit)

fit1 <- auto.arima(bit_bc, lambda="auto", max.order=10,
                               stepwise=FALSE, approximation = FALSE)
fit1$aicc
summary(fit1)

checkresiduals(fit)
checkresiduals(fit1)

autoplot(forecast(fit1, h=30)) +
  ylab("Bitcoin Price") + xlab("Days")+ggtitle("ARIMA forecast for 30 days")
autoplot(forecast(fit1, h=120)) +
  ylab("Bitcoin Price") + xlab("Days")+ggtitle("ARIMA forecast for 120 days")

accuracy(fit1)

#if independently distributed
tsdiag(fit1)
Box.test(fit1$residuals,lag=1,type="Ljung-Box")
Box.test(fit1$residuals, type="Ljung-Box")
```

  
  
  

```{r pressure, echo=TRUE, paged.print=TRUE}
#prediction based on previous 365 days record

s2020 <- bit[3570:3932,]

bit2 <- ts(s2020$Price)
bit2

autoplot(bit2)+ ylab("Bitcoin Close Price") + xlab("Days")+ggtitle("Price in 2020")

#max price in the previous year
max(bit2)

bit2_bc <- BoxCox(bit2,lambda="auto")
autoplot(bit2_bc)+ ylab("Bitcoin Close Price") + xlab("Days")+ggtitle("Transformed Price in 2020")

bit2_bc %>% diff(lag=1) %>% ur.kpss() %>% summary()
bit2_bc  %>% diff(lag=1) %>% ndiffs()

ggtsdisplay(diff(bit2_bc,lag=1))

fit2 <- auto.arima(bit2_bc, lambda="auto")
fit2$aicc
summary(fit2)
checkresiduals(fit2)

autoplot(forecast(fit2, h=30)) +
  ylab("Bitcoin Price") + xlab("Days")+ggtitle("Prediction for next 30 days")

autoplot(forecast(fit2, h=120)) +
  ylab("Bitcoin Price") + xlab("Days")+ggtitle("Prediction for next 120 days")

```
  
  
  


```{r pressure, echo=TRUE, paged.print=TRUE}
#not using auto
#higher aicc
lm <- BoxCox.lambda(bit2)
bit2_bc <- BoxCox(bit2,lambda=lm)
autoplot(bit2_bc)

fit7 <- auto.arima(bit2_bc, lambda=lm)
fit7$aicc

#Prophet
library(prophet)
df <-data.frame(ds=bit$Date,y=as.numeric(bit$Price))


m <- prophet(df)
future <- make_future_dataframe(m, periods = 30)
forecast <- predict(m, future)
plot(m, forecast)
prophet_plot_components(m, forecast)

prophet_pred <- prophet(df,daily.seasonality=TRUE)
future <- make_future_dataframe(prophet_pred,periods=30)
fcastprophet<- predict(prophet_pred,future)

dataprediction <-data.frame(fcastprophet$ds,fcastprophet$yhat)
trainlen <- length(bit$Price)
dataprediction <- dataprediction[c(1:trainlen),]

ggplot()+
  geom_smooth(aes(x= dataprediction$fcastprophet.ds,y=bit$Price),
              colour="blue",level=0.99,fill="#69b3a2",se=T)+
  geom_point(aes(x= dataprediction$fcastprophet.ds,y=dataprediction$fcastprophet.yhat))+
  xlab("ds")+
  ylab("y= GSPC.Close")+
  ggtitle("Training Prediction vs. Real Data:Prophet")

accuracy(dataprediction$fcastprophet.yhat,df$y)


```

```{r pressure, echo=TRUE, paged.print=TRUE}
#for the last 1 year
df <-data.frame(ds=s2020$Date, y=as.numeric(s2020$Price))
bit2

m <- prophet(df,daily.seasonality=TRUE,yearly.seasonality=TRUE)
future <- make_future_dataframe(m, periods = 30)
forecast <- predict(m, future)
plot(m, forecast)

prophet_plot_components(m, forecast)

prophet_pred <- prophet(df,daily.seasonality=TRUE,yearly.seasonality=TRUE)
future <- make_future_dataframe(prophet_pred,periods=30)
fcastprophet<- predict(prophet_pred,future)

dataprediction <-data.frame(fcastprophet$ds,fcastprophet$yhat)
trainlen <- length(s2020$Price)
dataprediction <- dataprediction[c(1:trainlen),]

ggplot()+
  geom_smooth(aes(x= dataprediction$fcastprophet.ds,y=s2020$Price),
              colour="blue",level=0.99,fill="#69b3a2",se=T)+
  geom_point(aes(x= dataprediction$fcastprophet.ds,y=dataprediction$fcastprophet.yhat))+
  xlab("ds")+
  ylab("y= GSPC.Close")+
  ggtitle("Training Prediction vs. Real Data:Prophet")

accuracy(dataprediction$fcastprophet.yhat,df$y)

#Feedforward 

lambda = BoxCox.lambda(bit$Price)
dnn_fit = nnetar(bit$Price,lambda=lambda)
dnn_fit

fcast = forecast(dnn_fit,PI=T,h=30)
autoplot(fcast)+ggtitle("Feed-forward NN 30 days based on all data")

fcast = forecast(dnn_fit,PI=T,h=120)
autoplot(fcast)+ggtitle("Feed-forward NN 120 days based on all data")

#nn for 1 year

lambda = BoxCox.lambda(s2020$Price)
dnn_fit = nnetar(s2020$Price,lambda=lambda)
dnn_fit

fcast = forecast(dnn_fit,PI=T,h=30)
autoplot(fcast)+ggtitle("Feed-forward NN 30 days based on 1 year data")

fcast1 = forecast(dnn_fit,PI=T,h=120)
autoplot(fcast1)+ggtitle("Feed-forward NN 120 days based on 1 year data")

```

```{r pressure, echo=TRUE, paged.print=TRUE}
#ets model

fit.ets <- ets(bit1, lambda="auto")
fit.ets
checkresiduals(fit.ets)
autoplot(forecast(fit.ets, h=30)) +
  ylab("Bitcoin") + xlab("Days")+ggtitle("ETS model 30 days based on all data")
autoplot(forecast(fit.ets, h=120)) +
  ylab("Bitcoin") + xlab("Days")+ggtitle("ETS model 120 days based on all data")

fit.ets1 <- ets(bit2, lambda="auto")
fit.ets1
checkresiduals(fit.ets1)
autoplot(forecast(fit.ets1, h=30)) +
  ylab("Bitcoin") + xlab("Days")+ggtitle("ETS model 30 days based on 1 year data")
autoplot(forecast(fit.ets1, h=120)) +
 ylab("Bitcoin") + xlab("Days")+ggtitle("ETS model 30 days based on 1 year data")

```
